Updated enable/disable card scripts to work nice with multiple acpi_call's

diff --git a/install-files/contrib/power_off_on/disablecard b/install-files/contrib/power_off_on/disablecard
--- a/install-files/contrib/power_off_on/disablecard
+++ b/install-files/contrib/power_off_on/disablecard
@@ -2,28 +2,45 @@
 
 # This script should contain the command(s) nessesary to switch off the nVidia card.
 
+acpi_call () {
+	echo "$*" > /proc/acpi/call
+	result=$(cat /proc/acpi/call)
+	case "$result" in
+	    failed)
+		echo "acpi_call $* failed."
+		final=$(( $final & 0 ))
+		;;
+	    ok)
+		echo "acpi_call $* succeded."
+		final=$(( $final & 1 ))
+		;;
+	esac
+}
+
 rmmod nvidia
 
 if lsmod | grep -q nvidia; then
-	echo "Error: could not unload nvidia module, leaving card turned on."
-	exit
+	echo "Error: could not unload nvidia module, leaving card turned on." 1>&2
+	exit 1
 fi
 
 modprobe acpi_call
 
 if ! lsmod | grep -q acpi_call; then
-	echo "Error: acpi_call module not loaded."
-	exit
+	echo "Error: acpi_call module not loaded." 1>&2
+	exit 1
 fi
 
-acpi_call () {
-	echo "$*" > /proc/acpi/call
-	result=$(cat /proc/acpi/call)
-	case "$result" in
-		failed*) echo "Disabling nVidia card failed."  ;;
-		ok*) echo "Disabling nVidia card succeded." ;;
-	esac
-}
+final=1
 
-# Replace this command string depending on your laptop model.
-echo $(acpi_call "\_SB_.PCI0.PEGR.GFX0._PS3")
+# Replace these command strings depending on your laptop model.
+acpi_call "\_SB.PCI0.LPCB.EC0.TSDS"
+acpi_call "\_SB.PCI0.PEGR.GFX0.DOFF"
+
+if [ $final = 1 ]; then
+	echo "Disabling nVidia card succeded."
+	exit 0
+else
+	echo "Disabling nVidia card failed."
+	exit 1
+fi
diff --git a/install-files/contrib/power_off_on/enablecard b/install-files/contrib/power_off_on/enablecard
--- a/install-files/contrib/power_off_on/enablecard
+++ b/install-files/contrib/power_off_on/enablecard
@@ -2,23 +2,32 @@
 
 # This script should contain the command(s) nessesary to switch on the nVidia card.
 
-modprobe acpi_call
-
-if ! lsmod | grep -q acpi_call; then
-	echo "Error: acpi_call module not loaded."
-	exit
-fi
-
 acpi_call () {
 	echo "$*" > /proc/acpi/call
 	result=$(cat /proc/acpi/call)
 	case "$result" in
-		failed*) echo "Enabling nVidia card failed." ;;
-		ok*) echo "Enabling nVidia card succeded." ;;
+		failed) echo "acpi_call $* failed." ;;
+		ok) echo "acpi_call $* succeded." ;;
 	esac
 }
 
-# Replace this command string depending on your laptop model.
-echo $(acpi_call "\_SB_.PCI0.PEGR.GFX0._PS0")
+modprobe acpi_call
+
+if ! lsmod | grep -q acpi_call; then
+	echo "Error: acpi_call module not loaded." 1>&2
+	exit 1
+fi
+
+# Replace these command strings depending on your laptop model.
+acpi_call "\_SB.PCI0.PEGR.GFX0.DON"
+acpi_call "\_SB.PCI0.LPCB.EC0.TSES"
 
 modprobe nvidia
+
+if lsmod | grep -q nvidia; then
+	echo "Enabling nVidia card succeded."
+	exit 0
+else
+	echo "Enabling nVidia card failed."
+	exit 1
+fi
