Added verbose option for optirun. Shut of successfull acpi_call's by default.

diff --git a/install-files/contrib/power_off_on/K53SJ/disablecard b/install-files/contrib/power_off_on/K53SJ/disablecard
--- a/install-files/contrib/power_off_on/K53SJ/disablecard
+++ b/install-files/contrib/power_off_on/K53SJ/disablecard
@@ -7,15 +7,19 @@ acpi_call () {
 	result=$(cat /proc/acpi/call)
 	case "$result" in
 	    failed)
-		echo "acpi_call $* failed."
+		echo "acpi_call $* failed." 1>&2
 		final=$(( $final & 0 ))
 		;;
 	    ok)
-		echo "acpi_call $* succeded."
+		if [ "$OPT_VERBOSE" = "yes" ]; then
+			echo "acpi_call $* succeded."
+		fi
 		final=$(( $final & 1 ))
 		;;
 	    *)
-		echo "acpi_call $* returned $result."
+		if [ "$OPT_VERBOSE" = "yes" ]; then
+			echo "acpi_call $* returned $result."
+		fi
 		final=$(( $final & 1 ))
 		;;
 	esac
diff --git a/install-files/contrib/power_off_on/K53SJ/enablecard b/install-files/contrib/power_off_on/K53SJ/enablecard
--- a/install-files/contrib/power_off_on/K53SJ/enablecard
+++ b/install-files/contrib/power_off_on/K53SJ/enablecard
@@ -6,9 +6,9 @@ acpi_call () {
 	echo "$*" > /proc/acpi/call
 	result=$(cat /proc/acpi/call)
 	case "$result" in
-		failed) echo "acpi_call $* failed." ;;
-		ok) echo "acpi_call $* succeded." ;;
-		*) echo "acpi_call $* returned $result." ;;
+		failed) echo "acpi_call $* failed." 1>&2 ;;
+		ok) if [ "$OPT_VERBOSE" = "yes" ]; then echo "acpi_call $* succeded."; fi ;;
+		*) if [ "$OPT_VERBOSE" = "yes" ]; then echo "acpi_call $* returned $result."; fi ;;
 	esac
 }
 
