Added experimnetal nouveau support. Right now it's just PoC and not suitable for daily use. Also nouveau lacks support of modern cards and most of GTX 400/500 won't work. Bumped version number.

diff --git a/install-files/contrib/power_off_on/XPS_L501X__/disablecard b/install-files/contrib/power_off_on/XPS_L501X__/disablecard
--- a/install-files/contrib/power_off_on/XPS_L501X__/disablecard
+++ b/install-files/contrib/power_off_on/XPS_L501X__/disablecard
@@ -2,6 +2,12 @@
 
 # This script should contain the command(s) necessary to switch off the nVidia card.
 
+if [ -r /etc/default/debumblebee ]; then
+	. /etc/default/debumblebee
+else
+	MODULE=nvidia
+fi
+
 acpi_call () {
 	echo "$*" > /proc/acpi/call
 	result=$(cat /proc/acpi/call)
@@ -25,10 +31,10 @@ acpi_call () {
 	esac
 }
 
-rmmod nvidia
+rmmod $MODULE
 
-if lsmod | grep -q nvidia; then
-	echo "Error: could not unload nvidia module, leaving card turned on." 1>&2
+if lsmod | grep -q $MODULE; then
+	echo "Error: could not unload $MODULE module, leaving card turned on." 1>&2
 	exit 1
 fi
 
diff --git a/install-files/debian/debumblebee b/install-files/debian/debumblebee
--- a/install-files/debian/debumblebee
+++ b/install-files/debian/debumblebee
@@ -17,17 +17,25 @@
 if [ -r /etc/default/debumblebee ]; then
 	. /etc/default/debumblebee
 else
+	MODULE=nvidia
 	VGL_DISPLAY=:8
 fi
 
 PATH=/sbin:/usr/local/sbin:/usr/sbin:/bin:/usr/local/bin:/usr/bin
-LD_LIBRARY_PATH=/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/nvidia
 DESC="Optimus X server"
 NAME=debumblebee
 DAEMON=/usr/bin/X
-DAEMON_ARGS="-config /etc/X11/xorg.conf.nvidia -modulepath /usr/local/lib/debumblebee,/usr/lib/xorg/modules -sharevts $VGL_DISPLAY"
 PIDFILE=/tmp/.X${VGL_DISPLAY#?}-lock
 SCRIPTNAME=/etc/init.d/$NAME
+if [ $MODULE = nvidia ]; then
+	LD_LIBRARY_PATH=/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`/nvidia
+	DAEMON_ARGS="-config /etc/X11/xorg.conf.nvidia -modulepath /usr/local/lib/debumblebee,/usr/lib/xorg/modules -sharevts $VGL_DISPLAY"
+elif [ $MODULE = nouveau ]; then
+	DAEMON_ARGS="-config /etc/X11/xorg.conf.nouveau -sharevts $VGL_DISPLAY"
+else
+	echo "Error: unknown MODULE option." 1>&2
+	exit 1
+fi
 
 . /lib/lsb/init-functions
 
