Updated Dell XPS L501X scripts

diff --git a/install-files/contrib/power_off_on/XPS_L501X__/disablecard b/install-files/contrib/power_off_on/XPS_L501X__/disablecard
--- a/install-files/contrib/power_off_on/XPS_L501X__/disablecard
+++ b/install-files/contrib/power_off_on/XPS_L501X__/disablecard
@@ -3,36 +3,40 @@
 # This script should contain the command(s) necessary to switch off the nVidia card.
 
 acpi_call () {
-    echo "$*" > /proc/acpi/call
-    result=$(cat /proc/acpi/call)
-    case "$result" in
-        failed)
-        echo "acpi_call $* failed."
-        final=$(( $final & 0 ))
-        ;;
-        ok)
-        echo "acpi_call $* succeded."
-        final=$(( $final & 1 ))
-        ;;
-        *)
-        echo "acpi_call $* returned $result."
-        final=$(( $final & 1 ))
-        ;;
-    esac
+	echo "$*" > /proc/acpi/call
+	result=$(cat /proc/acpi/call)
+	case "$result" in
+	    failed)
+		echo "acpi_call $* failed." 1>&2
+		final=$(( $final & 0 ))
+		;;
+	    ok)
+		if [ "$OPT_VERBOSE" = "yes" ]; then
+			echo "acpi_call $* succeded."
+		fi
+		final=$(( $final & 1 ))
+		;;
+	    *)
+		if [ "$OPT_VERBOSE" = "yes" ]; then
+			echo "acpi_call $* returned $result."
+		fi
+		final=$(( $final & 1 ))
+		;;
+	esac
 }
 
 rmmod nvidia
 
 if lsmod | grep -q nvidia; then
-    echo "Error: could not unload nvidia module, leaving card turned on." 1>&2
-    exit 1
+	echo "Error: could not unload nvidia module, leaving card turned on." 1>&2
+	exit 1
 fi
 
 modprobe acpi_call
 
 if ! lsmod | grep -q acpi_call; then
-    echo "Error: acpi_call module not loaded." 1>&2
-    exit 1
+	echo "Error: acpi_call module not loaded." 1>&2
+	exit 1
 fi
 
 final=1
@@ -43,9 +47,9 @@ acpi_call "\_SB.PCI0.P0P2.PEGP.NVOP 0 0x100 0x1A {255,255,255,255}"
 acpi_call "\_SB.PCI0.P0P2.PEGP._PS3"
 
 if [ $final = 1 ]; then
-    echo "Disabling nVidia card succeded."
-    exit 0
+	echo "Disabling nVidia card succeded."
+	exit 0
 else
-    echo "Disabling nVidia card failed."
-    exit 1
+	echo "Disabling nVidia card failed."
+	exit 1
 fi
diff --git a/install-files/contrib/power_off_on/XPS_L501X__/enablecard b/install-files/contrib/power_off_on/XPS_L501X__/enablecard
--- a/install-files/contrib/power_off_on/XPS_L501X__/enablecard
+++ b/install-files/contrib/power_off_on/XPS_L501X__/enablecard
@@ -3,20 +3,20 @@
 # This script should contain the command(s) necessary to switch on the nVidia card.
 
 acpi_call () {
-    echo "$*" > /proc/acpi/call
-    result=$(cat /proc/acpi/call)
-    case "$result" in
-        failed) echo "acpi_call $* failed." ;;
-        ok) echo "acpi_call $* succeded." ;;
-        *) echo "acpi_call $* returned $result." ;;
-    esac
+	echo "$*" > /proc/acpi/call
+	result=$(cat /proc/acpi/call)
+	case "$result" in
+		failed) echo "acpi_call $* failed." 1>&2 ;;
+		ok) if [ "$OPT_VERBOSE" = "yes" ]; then echo "acpi_call $* succeded."; fi ;;
+		*) if [ "$OPT_VERBOSE" = "yes" ]; then echo "acpi_call $* returned $result."; fi ;;
+	esac
 }
 
 modprobe acpi_call
 
 if ! lsmod | grep -q acpi_call; then
-    echo "Error: acpi_call module not loaded." 1>&2
-    exit 1
+	echo "Error: acpi_call module not loaded." 1>&2
+	exit 1
 fi
 
 # Replace this command string depending on your laptop model.
@@ -26,9 +26,9 @@ acpi_call "\_SB.PCI0.P0P2.PEGP._PS0"
 modprobe nvidia
 
 if lsmod | grep -q nvidia; then
-    echo "Enabling nVidia card succeded."
-    exit 0
+	echo "Enabling nVidia card succeded."
+	exit 0
 else
-    echo "Enabling nVidia card failed."
-    exit 1
+	echo "Enabling nVidia card failed."
+	exit 1
 fi
